## 1. caughtError

在执行 `renderRoot` 的时 `performUnitOfWork` 的过程中可能会产生错误，出现错误当前 `nextUnitOfWork`的 `fiber`的渲染会终止，然后进入 `catch` 的部分：

[react-reconciler/src/ReactFiberScheduler.js]()

```ts
function renderRoot(
  root: FiberRoot,
  isYieldy: boolean,
  isExpired: boolean,
): void {
  do {
    try {
      while (nextUnitOfWork !== null) {
        nextUnitOfWork = performUnitOfWork(nextUnitOfWork);
      }
    } catch (thrownValue) {
      if (nextUnitOfWork === null) { // 致命错误，nextUnitOfWork即使抛出错误也不应该 == null
        // This is a fatal error.
        didFatal = true;
        onUncaughtError(thrownValue);
      } else {
        const failedUnitOfWork: Fiber = nextUnitOfWork;
        const sourceFiber: Fiber = nextUnitOfWork;
        let returnFiber = sourceFiber.return;
        if (returnFiber === null) { // 致命错误
          didFatal = true;
          onUncaughtError(thrownValue);
        } else {
          throwException(
            root,
            returnFiber,
            sourceFiber,
            thrownValue,
            nextRenderExpirationTime,
          );
          nextUnitOfWork = completeUnitOfWork(sourceFiber);
          continue;
        }
      }
    }
    break;
  } while (true);
}
```

错误处理这部分包括下面几种情况：

+ `nextUnitOfWork === null`：只有 `completeUnitOfWork` 执行到 `FiberRoot` 退出的时候这个值会为 `null` ，但是个时候不可能抛出错误，所以一旦出现这种情况，表示这个是一个致命错误，进行错误回调之后要跳出循环。
+ `returnFiber === null`：同样 `returnFiber` 为 `null` 的时间点也不肯能抛出错误，所以这也是致命的。
+ 其他错误走 `throwException` 进行处理，同时出现错误的这个 `fiber` 的子节点就不应该继续渲染了，所以直接使用 `completeUnitOfWork` 避开子树走兄弟。

### 2.1 onUncaughtError

出现致命错误会打印提示，清空任务，设置一些标识位：

[react-reconciler/src/ReactFiberScheduler.js]()

```ts
function onUncaughtError(error: mixed) {
  invariant(
    nextFlushedRoot !== null,
    'Should be working on a root. This error is likely caused by a bug in ' +
      'React. Please file an issue.',
  );
  // Unschedule this root so we don't work on it again until there's
  // another update.
  nextFlushedRoot.expirationTime = NoWork;
  if (!hasUnhandledError) {
    hasUnhandledError = true;
    unhandledError = error;
  }
}
```

### 2.2 throwException

`throwException` 这里先做个 `Incomplete` 的标记，然后清空 `effect`然后这个函数创建了一个 `Captured Error` 进入 `do while`：

+ 找到一个 `HostRoot`：标记 `ShouldCapture`为 `effectTag`，因为这个节点要在 `commit` 阶段被使用，所以还要设置 `expirationTime`，最后构建一个 `update` 然后推入 `capturedUpdate`里。
+ 找到一个 `ClassComponent`：判断这个节点的`ClassComponent` 有没有`getDerivedStateFromError` 或者 `componentDidCatch` 这两个生命周期，如果有流程和 `HostRoot` 基本一致。

```ts
function throwException(
  root: FiberRoot,
  returnFiber: Fiber,
  sourceFiber: Fiber,
  value: mixed,
  renderExpirationTime: ExpirationTime,
) {
  // The source fiber did not complete.
  sourceFiber.effectTag |= Incomplete;
  // Its effect list is no longer valid.
  sourceFiber.firstEffect = sourceFiber.lastEffect = null;
  renderDidError();
  value = createCapturedValue(value, sourceFiber);
  let workInProgress = returnFiber;
  do {
    switch (workInProgress.tag) {
      case HostRoot: {
        const errorInfo = value;
        workInProgress.effectTag |= ShouldCapture;
        workInProgress.expirationTime = renderExpirationTime;
        const update = createRootErrorUpdate(
          workInProgress,
          errorInfo,
          renderExpirationTime,
        );
        enqueueCapturedUpdate(workInProgress, update);
        return;
      }
      case ClassComponent:
        // Capture and retry
        const errorInfo = value;
        const ctor = workInProgress.type;
        const instance = workInProgress.stateNode;
        if (
          (workInProgress.effectTag & DidCapture) === NoEffect &&
          (typeof ctor.getDerivedStateFromError === 'function' ||
            (instance !== null &&
              typeof instance.componentDidCatch === 'function' &&
              !isAlreadyFailedLegacyErrorBoundary(instance)))
        ) {
          workInProgress.effectTag |= ShouldCapture;
          workInProgress.expirationTime = renderExpirationTime;
          // Schedule the error boundary to re-render using updated state
          const update = createClassErrorUpdate(
            workInProgress,
            errorInfo,
            renderExpirationTime,
          );
          enqueueCapturedUpdate(workInProgress, update);
          return;
        }
        break;
      default:
        break;
    }
    workInProgress = workInProgress.return;
  } while (workInProgress !== null);
}
```

```ts
function renderDidError() {
  nextRenderDidError = true;
}
```

#### 2.2.1 createRootErrorUpdate

构建一个  `CaptureUpdate`：

[react-reconciler/src/ReactFiberUnwindWork.js]()

```ts
function createRootErrorUpdate(
  fiber: Fiber,
  errorInfo: CapturedValue<mixed>,
  expirationTime: ExpirationTime,
): Update<mixed> {
  const update = createUpdate(expirationTime);
  // Unmount the root by rendering null.
  update.tag = CaptureUpdate;
  // Caution: React DevTools currently depends on this property
  // being called "element".
  update.payload = {element: null};
  const error = errorInfo.value;
  update.callback = () => {
    onUncaughtError(error);
    logError(fiber, errorInfo);
  };
  return update;
}
```

#### 2.2.2 createClassErrorUpdate

注意这里有个生命周期回调：

[react-reconciler/src/ReactFiberUnwindWork.js]()

```ts
function createClassErrorUpdate(
  fiber: Fiber,
  errorInfo: CapturedValue<mixed>,
  expirationTime: ExpirationTime,
): Update<mixed> {
  const update = createUpdate(expirationTime);
  update.tag = CaptureUpdate;
  const getDerivedStateFromError = fiber.type.getDerivedStateFromError;
  if (typeof getDerivedStateFromError === 'function') {
    const error = errorInfo.value;
    update.payload = () => {
      return getDerivedStateFromError(error);
    };
  }
```

## 2. unwindWork

出现了错误之后再次进入 `completeUnitOfWork` 由于 `workInProgress.effectTag` 被设置了 `InComplete`这次走的就是 `unwindWork` 这个分支了，

```ts
function completeUnitOfWork(workInProgress: Fiber): Fiber | null {
  // Attempt to complete the current unit of work, then move to the
  // next sibling. If there are no more siblings, return to the
  // parent fiber.
  while (true) {
    // The current, flushed, state of this fiber is the alternate.
    // Ideally nothing should rely on this, but relying on it here
    // means that we don't need an additional field on the work in
    // progress.
    const current = workInProgress.alternate;

    const returnFiber = workInProgress.return;   // 父节点
    const siblingFiber = workInProgress.sibling; // 兄弟节点

    if ((workInProgress.effectTag & Incomplete) === NoEffect) {
      // This fiber completed.
      nextUnitOfWork = completeWork(
        current,
        workInProgress,
        nextRenderExpirationTime,
      );
      resetChildExpirationTime(workInProgress, nextRenderExpirationTime);

      if (
        returnFiber !== null &&
        // Do not append effects to parents if a sibling failed to complete
        (returnFiber.effectTag & Incomplete) === NoEffect
      ) {
        if (returnFiber.firstEffect === null) {
          returnFiber.firstEffect = workInProgress.firstEffect;
        }
        if (workInProgress.lastEffect !== null) {
          if (returnFiber.lastEffect !== null) {
            returnFiber.lastEffect.nextEffect = workInProgress.firstEffect;
          }
          returnFiber.lastEffect = workInProgress.lastEffect;
        }
        const effectTag = workInProgress.effectTag;
        // Skip both NoWork and PerformedWork tags when creating the effect list.
        // PerformedWork effect is read by React DevTools but shouldn't be committed.
        if (effectTag > PerformedWork) {
          if (returnFiber.lastEffect !== null) {
            returnFiber.lastEffect.nextEffect = workInProgress;
          } else {
            returnFiber.firstEffect = workInProgress;
          }
          returnFiber.lastEffect = workInProgress;
        }
      }
      if (siblingFiber !== null) {
        // If there is more work to do in this returnFiber, do that next.
        return siblingFiber;
      } else if (returnFiber !== null) {
        // If there's no more work in this returnFiber. Complete the returnFiber.
        workInProgress = returnFiber;
        continue;
      } else {
        // We've reached the root.
        return null;
      }
    } else {
      // This fiber did not complete because something threw. Pop values off
      // the stack without entering the complete phase. If this is a boundary,
      // capture values if possible.
      const next = unwindWork(workInProgress, nextRenderExpirationTime);
      // Because this fiber did not complete, don't reset its expiration time.
      if (workInProgress.effectTag & DidCapture) {
        // Restarting an error boundary
        stopFailedWorkTimer(workInProgress);
      } else {
        stopWorkTimer(workInProgress);
      }

      if (next !== null) {
        // If completing this work spawned new work, do that next. We'll come
        // back here again.
        // Since we're restarting, remove anything that is not a host effect
        // from the effect tag.
        next.effectTag &= HostEffectMask;
        return next;
      }
      if (returnFiber !== null) {
        // Mark the parent fiber as incomplete and clear its effect list.
        returnFiber.firstEffect = returnFiber.lastEffect = null;
        returnFiber.effectTag |= Incomplete;
      }

      if (siblingFiber !== null) {
        // If there is more work to do in this returnFiber, do that next.
        return siblingFiber;
      } else if (returnFiber !== null) {
        // If there's no more work in this returnFiber. Complete the returnFiber.
        workInProgress = returnFiber;
        continue;
      } else {
        return null;
      }
    }
  }

  return null;
}
```

### 2.1 unwindWork

这个函数用于向上找到第一个 `ClassComponent` 或者一个 `HostRoot`，只有这个函数能处理抛出的错误，这个组件的 `effectTag` 会取消 `ShouldCapture ` 添加 `DidCapture`：

```ts
function unwindWork(
  workInProgress: Fiber,
  renderExpirationTime: ExpirationTime,
) {
  switch (workInProgress.tag) {
    case ClassComponent: {
      const Component = workInProgress.type;
      if (isLegacyContextProvider(Component)) {
        popLegacyContext(workInProgress);
      }
      const effectTag = workInProgress.effectTag;
      if (effectTag & ShouldCapture) {
        workInProgress.effectTag = (effectTag & ~ShouldCapture) | DidCapture;
        return workInProgress;
      }
      return null;
    }
    case HostRoot: {
      popHostContainer(workInProgress);
      popTopLevelLegacyContextObject(workInProgress);
      const effectTag = workInProgress.effectTag;
      invariant(
        (effectTag & DidCapture) === NoEffect,
        'The root failed to unmount after an error. This is likely a bug in ' +
          'React. Please file an issue.',
      );
      workInProgress.effectTag = (effectTag & ~ShouldCapture) | DidCapture;
      return workInProgress;
    }
    case HostComponent: {
      popHostContext(workInProgress);
      return null;
    }
    case SuspenseComponent: {
      // ...
    }
    case HostPortal:
      popHostContainer(workInProgress);
      return null;
    case ContextProvider:
      popProvider(workInProgress);
      return null;
    default:
      return null;
  }
}
```

命中 `ClassComponent` 或者 `HostRoot`，`next` 就会被赋值， `completeUnitOfWork` 就会退出返回 `next`:

```ts
function completeUnitOfWork(workInProgress: Fiber): Fiber | null {
  while(true) {
    /...
    if (next !== null) {
      const next = unwindWork(workInProgress, nextRenderExpirationTime);
      
      next.effectTag &= HostEffectMask;
      return next;
    }
    /...
  }
}
```

然后 `workLoop` 中的 `nextUnitOfWork` 就会被赋予值为 `next`，然后再走 `performUnitOfWork`，之后重新 `beginWork` 渲染，命中 `HostComponent`  或者 `HostRoot` 之后由于 `didCaptureError` 会执行 `forceUnmountCurrentAndReconcile` ：

```ts
function finishClassComponent() {
	if (current !== null && didCaptureError) {
    // If we're recovering from an error, reconcile without reusing any of
    // the existing children. Conceptually, the normal children and the children
    // that are shown on error are two different sets, so we shouldn't reuse
    // normal children even if their identities match.
    forceUnmountCurrentAndReconcile(
      current,
      workInProgress,
      null,
      renderExpirationTime,
    );
  }
}
```

这个函数会卸载组件并且重新更新，由于我们传入的 `nextChildren` 是 `null` 所以错误处理的那个组件不会在渲染任何的子节点，只会执行之前塞到 `CaptureUpdate` 里的回调函数(生命周期函数)。

```ts
function forceUnmountCurrentAndReconcile(
  current: Fiber,
  workInProgress: Fiber,
  nextChildren: any,
  renderExpirationTime: ExpirationTime,
) {
  // This function is fork of reconcileChildren. It's used in cases where we
  // want to reconcile without matching against the existing set. This has the
  // effect of all current children being unmounted; even if the type and key
  // are the same, the old child is unmounted and a new child is created.
  
  // To do this, we're going to go through the reconcile algorithm twice. In
  // the first pass, we schedule a deletion for all the current children by
  // passing null.
  workInProgress.child = reconcileChildFibers(
    workInProgress,
    current.child,
    null,
    renderExpirationTime,
  );
  // In the second pass, we mount the new children. The trick here is that we
  // pass null in place of where we usually pass the current child set. This has
  // the effect of remounting all children regardless of whether their their
  // identity matches.
  workInProgress.child = reconcileChildFibers(
    workInProgress,
    null,
    nextChildren,
    renderExpirationTime,
  );
}
```

最后由于 `InComplete` 已经被取消了不会重复进入 `unwindOfWork`，`completeUnitOfWork` 会走这个错误处理组件的兄弟节点：

```ts
function renderRoot() {
  /...
  do {
    try {
      while (nextUnitOfWork !== null) {
        nextUnitOfWork = performUnitOfWork(nextUnitOfWork);
      }
    } catch() {
      /...
    }
  }
  /...
}

```

